export enum StatusCode {
    BEGIN_LOGIN,
    LOGIN_FAILED,
    LOGIN_SUCCESS,
    DECRYPT_FAILED,
    DECRYPT_SUCCESS,
    ENCRYPT_FAILED,
    ENCRYPT_SUCCESS,
    FILE_EXIST,
    FILE_NOT_EXIST,
    CHEKC_FILE_EXIST_FAILED,
    GET_FILE_CONTENT_SUCCESS,
    GET_FILE_CONTENT_FAILED,
    SAVE_FILE_SUCCESS,
    SAVE_FILE_FAILED
};